#pragma once

#define ZORDER_LOBBY_TOOLTIP_SHADOW	10
#define ZORDER_LOBBY_TOOLTIP_BACK	11
#define ZORDER_LOBBY_TOOLTIP		12
#define ZORDER_LOBBY_TOOLTIP_TEXT	13

#define ZORDER_INGAME_PLAY_DISTANCE_TEXT 10
#define ZORDER_INGAME_START_COUNT_TEXT 11

#define ZORDER_LOADING 100