#pragma once

#define ZORDER_LOBBY_PLAYER_CHECK_BACK	4
#define ZORDER_LOBBY_PLAYER				5
#define ZORDER_LOBBY_PLAYER_ITEM_ICON	6

#define ZORDER_LOBBY_MY_ITEM_SLOT	7
#define ZORDER_LOBBY_MY_ITEM_ICON	8
#define ZORDER_LOBBY_MY_ITEM_BUTTON	9

#define ZORDER_LOBBY_TOOLTIP_SHADOW	10
#define ZORDER_LOBBY_TOOLTIP_BACK	11
#define ZORDER_LOBBY_TOOLTIP		12
#define ZORDER_LOBBY_TOOLTIP_TEXT	13

// InGame
#define ZORDER_INGAME_PLAY_OTHER_NAME_TAG	7
#define ZORDER_INGAME_PLAY_OTHER_HP_BACK	8
#define ZORDER_INGAME_PLAY_OTHER_HP			9
#define ZORDER_INGAME_PLAY_DISTANCE_TEXT	10
#define ZORDER_INGAME_START_COUNT_TEXT		11

// Loading
#define ZORDER_LOADING_BACK 100
#define ZORDER_LOADING 101

#define ZORDER_FPS 102